Codebook - Human Activity Recognition Using Smartphones
========================================================
Coursera - Getting and Cleaning Data - Assingment


Overview
--------
This codebook describes the assignment task including the underlying data, transformations or work related to the cleaning of the data, and variables.
The objective is to create a tidy dataset for later analysis.

The input dataset reflects the results from a human activity recognition study. The data was build from the recordings of 30 individualts performing daily activities while carrying a waist-mounted smartphone with embedded interial sensors.
Information on the study is available at: 
http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones.

Input Data Set Information
--------------------
Information on the Dataset can be found via the aformentioned webpage.

The dataset can be downloaded from: 
https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip


Data Preparation
----------------
The following steps have been performed to collect and clean the dataset for further analysis.

### Downloading the data
The data was downloaded from https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip and saved to the project folder.

The downloaded zip file is unzipped. The resulting folder is renamed to 'UCIHARDataset' to remove blank spaces from the folder name.

Note: if you want to run the script, please adapt the folder name accordingly.


Script run_analysis
-------------------
The script run_analysis performs the following operations:

### Step 0: configuration of project path
Specify the path to the project folder.
For the author's system this is: projectPath <- "~/__PERFORMANCE/Courses/GettingAndCleaningData/assignment/" on a Windows PC.

Note: you may need to adapt the settings.

### Step 1: merging of training and test data
The script reads in the training sets for the x, y, and subject data of the training and test experiments and stores the data in respective dataframes.
In particular,
* xTrain comprises 7352 records of 561 variables according to the features.txt file
* xTest  comprises 2947 records of 561 variables
* yTrain lists the activity (1 variable) for the 7352 records
* yTest lists the activity (1 variable) for the 2947 record
* subjectTrain decodes the individuals (1 variable, 1 through 30) executing the activity
* subjectTest decosed the individuals for each activity / measurements

The data is merged, resulting in dataframes
* xData, number of instances/records 10299 with 561 attributes
* yData, a 10299 * 1 data frame listing the activity identifier
* sData, a 10299 * 1 data frame listing the identifier of the person doing the activity

### Step 2: extraction of measurements for mean and standard deviation
The scripts reads in the feature.txt file and extracts the 66 features for the measurements on the mean and standard deviation. 

The xData dataframe is subsetted for this filtered feature set, yielding a 10299 * 66 dataframe. All xData measurments range between [-1,1].

The extracted features are listed in Appendix A.

### Step 3: recoding of activities
The scrpt reads in the activity_labels.txt file.

"Descriptive activity names" are generated by improving "human readability" of the activity codes, i.e. removal of "_" and change to lower case.
This creates a factor with 6 levels:
* "laying"
* "sitting"
* "standing"
* "walking"           
* "walking downstairs"
* "walking upstairs" 

yData is decoded with these activity names.

### Step 4: appropriate labelling of dataset, and creation and storage of tidy dataframe
The script, renames the
* column variables names of xData with the filtered 66 feature names
* column variable of sData to "subject"
* column variable of yData to "activity"

A first tidy 10299 * 68 data set is created by binding sData, yData, and xData yielding 
the subject identifier in the first column, the activity in the 2nd column, and the feature measurments in the following 66 columns.

subject identifier are integers between 1 and 30;
activity identifier comprise the factors mentioned above, totalling
                  activity   
     laying            :1944  
     sitting           :1777  
     standing          :1906  
     walking           :1722  
     walking downstairs:1406  
     walking upstairs  :1544
feature measurements range within [-1,1] interval, the variable names are listed in Appendix A.

The merged dataset is saved as 'tidyUCHARDataset.txt'; the structure of this dataset is given in Appendix B.

### step 5: average for each measurement per activity and subject
The script generates an aggregated dataset of dimenesion 180 * 68.

Column 1: subject identifier
COlumn 2: actiity label
Columns 3..68: averages of feature measurements for each subject and activity

As there are 30 subjects performing 6 activities, the 12099 total instances of measurements are aggregated into 180 averages as can be derived from the following listing.
      activity  
 laying            :30  
 sitting           :30  
 standing          :30  
 walking           :30  
 walking downstairs:30  
 walking upstairs  :30

This dataset is stored as 'tidyUCHARDatasetMeans.txt'. 
The structure is identical to Appendix B (as the values represent now means per subject and activity).



Appendix
--------

### Appendix A - features

tBodyAcc-mean()-X tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  tBodyAcc-std()-X  tBodyAcc-std()-Y  
 Min.   :-1.0000   Min.   :-1.00000   Min.   :-1.00000   Min.   :-1.0000   Min.   :-1.00000  
 1st Qu.: 0.2626   1st Qu.:-0.02490   1st Qu.:-0.12102   1st Qu.:-0.9924   1st Qu.:-0.97699  
 Median : 0.2772   Median :-0.01716   Median :-0.10860   Median :-0.9430   Median :-0.83503  
 Mean   : 0.2743   Mean   :-0.01774   Mean   :-0.10892   Mean   :-0.6078   Mean   :-0.51019  
 3rd Qu.: 0.2884   3rd Qu.:-0.01062   3rd Qu.:-0.09759   3rd Qu.:-0.2503   3rd Qu.:-0.05734  
 Max.   : 1.0000   Max.   : 1.00000   Max.   : 1.00000   Max.   : 1.0000   Max.   : 1.00000  
 
 tBodyAcc-std()-Z  tGravityAcc-mean()-X tGravityAcc-mean()-Y tGravityAcc-mean()-Z
 Min.   :-1.0000   Min.   :-1.0000      Min.   :-1.000000    Min.   :-1.00000    
 1st Qu.:-0.9791   1st Qu.: 0.8117      1st Qu.:-0.242943    1st Qu.:-0.11671    
 Median :-0.8508   Median : 0.9218      Median :-0.143551    Median : 0.03680    
 Mean   :-0.6131   Mean   : 0.6692      Mean   : 0.004039    Mean   : 0.09215    
 3rd Qu.:-0.2787   3rd Qu.: 0.9547      3rd Qu.: 0.118905    3rd Qu.: 0.21621    
 Max.   : 1.0000   Max.   : 1.0000      Max.   : 1.000000    Max.   : 1.00000    
 
 tGravityAcc-std()-X tGravityAcc-std()-Y tGravityAcc-std()-Z tBodyAccJerk-mean()-X
 Min.   :-1.0000     Min.   :-1.0000     Min.   :-1.0000     Min.   :-1.00000     
 1st Qu.:-0.9949     1st Qu.:-0.9913     1st Qu.:-0.9866     1st Qu.: 0.06298     
 Median :-0.9819     Median :-0.9759     Median :-0.9665     Median : 0.07597     
 Mean   :-0.9652     Mean   :-0.9544     Mean   :-0.9389     Mean   : 0.07894     
 3rd Qu.:-0.9615     3rd Qu.:-0.9464     3rd Qu.:-0.9296     3rd Qu.: 0.09131     
 Max.   : 1.0000     Max.   : 1.0000     Max.   : 1.0000     Max.   : 1.00000     
 
 tBodyAccJerk-mean()-Y tBodyAccJerk-mean()-Z tBodyAccJerk-std()-X tBodyAccJerk-std()-Y
 Min.   :-1.000000     Min.   :-1.000000     Min.   :-1.0000      Min.   :-1.0000     
 1st Qu.:-0.018555     1st Qu.:-0.031552     1st Qu.:-0.9913      1st Qu.:-0.9850     
 Median : 0.010753     Median :-0.001159     Median :-0.9513      Median :-0.9250     
 Mean   : 0.007948     Mean   :-0.004675     Mean   :-0.6398      Mean   :-0.6080     
 3rd Qu.: 0.033538     3rd Qu.: 0.024578     3rd Qu.:-0.2912      3rd Qu.:-0.2218     
 Max.   : 1.000000     Max.   : 1.000000     Max.   : 1.0000      Max.   : 1.0000     
 
 tBodyAccJerk-std()-Z tBodyGyro-mean()-X tBodyGyro-mean()-Y tBodyGyro-mean()-Z
 Min.   :-1.0000      Min.   :-1.00000   Min.   :-1.00000   Min.   :-1.00000  
 1st Qu.:-0.9892      1st Qu.:-0.04579   1st Qu.:-0.10399   1st Qu.: 0.06485  
 Median :-0.9543      Median :-0.02776   Median :-0.07477   Median : 0.08626  
 Mean   :-0.7628      Mean   :-0.03098   Mean   :-0.07472   Mean   : 0.08836  
 3rd Qu.:-0.5485      3rd Qu.:-0.01058   3rd Qu.:-0.05110   3rd Qu.: 0.11044  
 Max.   : 1.0000      Max.   : 1.00000   Max.   : 1.00000   Max.   : 1.00000  
 
 tBodyGyro-std()-X tBodyGyro-std()-Y tBodyGyro-std()-Z tBodyGyroJerk-mean()-X
 Min.   :-1.0000   Min.   :-1.0000   Min.   :-1.0000   Min.   :-1.00000      
 1st Qu.:-0.9872   1st Qu.:-0.9819   1st Qu.:-0.9850   1st Qu.:-0.11723      
 Median :-0.9016   Median :-0.9106   Median :-0.8819   Median :-0.09824      
 Mean   :-0.7212   Mean   :-0.6827   Mean   :-0.6537   Mean   :-0.09671      
 3rd Qu.:-0.4822   3rd Qu.:-0.4461   3rd Qu.:-0.3379   3rd Qu.:-0.07930      
 Max.   : 1.0000   Max.   : 1.0000   Max.   : 1.0000   Max.   : 1.00000      
 
 tBodyGyroJerk-mean()-Y tBodyGyroJerk-mean()-Z tBodyGyroJerk-std()-X tBodyGyroJerk-std()-Y
 Min.   :-1.00000       Min.   :-1.00000       Min.   :-1.0000       Min.   :-1.0000      
 1st Qu.:-0.05868       1st Qu.:-0.07936       1st Qu.:-0.9907       1st Qu.:-0.9922      
 Median :-0.04056       Median :-0.05455       Median :-0.9348       Median :-0.9548      
 Mean   :-0.04232       Mean   :-0.05483       Mean   :-0.7313       Mean   :-0.7861      
 3rd Qu.:-0.02521       3rd Qu.:-0.03168       3rd Qu.:-0.4865       3rd Qu.:-0.6268      
 Max.   : 1.00000       Max.   : 1.00000       Max.   : 1.0000       Max.   : 1.0000      
 
 tBodyGyroJerk-std()-Z tBodyAccMag-mean() tBodyAccMag-std() tGravityAccMag-mean()
 Min.   :-1.0000       Min.   :-1.0000    Min.   :-1.0000   Min.   :-1.0000      
 1st Qu.:-0.9926       1st Qu.:-0.9819    1st Qu.:-0.9822   1st Qu.:-0.9819      
 Median :-0.9503       Median :-0.8746    Median :-0.8437   Median :-0.8746      
 Mean   :-0.7399       Mean   :-0.5482    Mean   :-0.5912   Mean   :-0.5482      
 3rd Qu.:-0.5097       3rd Qu.:-0.1201    3rd Qu.:-0.2423   3rd Qu.:-0.1201      
 Max.   : 1.0000       Max.   : 1.0000    Max.   : 1.0000   Max.   : 1.0000      
 
 tGravityAccMag-std() tBodyAccJerkMag-mean() tBodyAccJerkMag-std() tBodyGyroMag-mean()
 Min.   :-1.0000      Min.   :-1.0000        Min.   :-1.0000       Min.   :-1.0000    
 1st Qu.:-0.9822      1st Qu.:-0.9896        1st Qu.:-0.9907       1st Qu.:-0.9781    
 Median :-0.8437      Median :-0.9481        Median :-0.9288       Median :-0.8223    
 Mean   :-0.5912      Mean   :-0.6494        Mean   :-0.6278       Mean   :-0.6052    
 3rd Qu.:-0.2423      3rd Qu.:-0.2956        3rd Qu.:-0.2733       3rd Qu.:-0.2454    
 Max.   : 1.0000      Max.   : 1.0000        Max.   : 1.0000       Max.   : 1.0000    
 
 tBodyGyroMag-std() tBodyGyroJerkMag-mean() tBodyGyroJerkMag-std() fBodyAcc-mean()-X
 Min.   :-1.0000    Min.   :-1.0000         Min.   :-1.0000        Min.   :-1.0000  
 1st Qu.:-0.9775    1st Qu.:-0.9923         1st Qu.:-0.9922        1st Qu.:-0.9913  
 Median :-0.8259    Median :-0.9559         Median :-0.9403        Median :-0.9456  
 Mean   :-0.6625    Mean   :-0.7621         Mean   :-0.7780        Mean   :-0.6228  
 3rd Qu.:-0.3940    3rd Qu.:-0.5499         3rd Qu.:-0.6093        3rd Qu.:-0.2646  
 Max.   : 1.0000    Max.   : 1.0000         Max.   : 1.0000        Max.   : 1.0000  
 
 fBodyAcc-mean()-Y fBodyAcc-mean()-Z fBodyAcc-std()-X  fBodyAcc-std()-Y   fBodyAcc-std()-Z 
 Min.   :-1.0000   Min.   :-1.0000   Min.   :-1.0000   Min.   :-1.00000   Min.   :-1.0000  
 1st Qu.:-0.9792   1st Qu.:-0.9832   1st Qu.:-0.9929   1st Qu.:-0.97689   1st Qu.:-0.9780  
 Median :-0.8643   Median :-0.8954   Median :-0.9416   Median :-0.83261   Median :-0.8398  
 Mean   :-0.5375   Mean   :-0.6650   Mean   :-0.6034   Mean   :-0.52842   Mean   :-0.6179  
 3rd Qu.:-0.1032   3rd Qu.:-0.3662   3rd Qu.:-0.2493   3rd Qu.:-0.09216   3rd Qu.:-0.3023  
 Max.   : 1.0000   Max.   : 1.0000   Max.   : 1.0000   Max.   : 1.00000   Max.   : 1.0000  
 
 fBodyAccJerk-mean()-X fBodyAccJerk-mean()-Y fBodyAccJerk-mean()-Z fBodyAccJerk-std()-X
 Min.   :-1.0000       Min.   :-1.0000       Min.   :-1.0000       Min.   :-1.0000     
 1st Qu.:-0.9912       1st Qu.:-0.9848       1st Qu.:-0.9873       1st Qu.:-0.9920     
 Median :-0.9516       Median :-0.9257       Median :-0.9475       Median :-0.9562     
 Mean   :-0.6567       Mean   :-0.6290       Mean   :-0.7436       Mean   :-0.6550     
 3rd Qu.:-0.3270       3rd Qu.:-0.2638       3rd Qu.:-0.5133       3rd Qu.:-0.3203     
 Max.   : 1.0000       Max.   : 1.0000       Max.   : 1.0000       Max.   : 1.0000     
 
 fBodyAccJerk-std()-Y fBodyAccJerk-std()-Z fBodyGyro-mean()-X fBodyGyro-mean()-Y
 Min.   :-1.0000      Min.   :-1.0000      Min.   :-1.0000    Min.   :-1.0000   
 1st Qu.:-0.9865      1st Qu.:-0.9895      1st Qu.:-0.9853    1st Qu.:-0.9847   
 Median :-0.9280      Median :-0.9590      Median :-0.8917    Median :-0.9197   
 Mean   :-0.6122      Mean   :-0.7809      Mean   :-0.6721    Mean   :-0.7062   
 3rd Qu.:-0.2361      3rd Qu.:-0.5903      3rd Qu.:-0.3837    3rd Qu.:-0.4735   
 Max.   : 1.0000      Max.   : 1.0000      Max.   : 1.0000    Max.   : 1.0000   
 
 fBodyGyro-mean()-Z fBodyGyro-std()-X fBodyGyro-std()-Y fBodyGyro-std()-Z fBodyAccMag-mean()
 Min.   :-1.0000    Min.   :-1.0000   Min.   :-1.0000   Min.   :-1.0000   Min.   :-1.0000   
 1st Qu.:-0.9851    1st Qu.:-0.9881   1st Qu.:-0.9808   1st Qu.:-0.9862   1st Qu.:-0.9847   
 Median :-0.8877    Median :-0.9053   Median :-0.9061   Median :-0.8915   Median :-0.8755   
 Mean   :-0.6442    Mean   :-0.7386   Mean   :-0.6742   Mean   :-0.6904   Mean   :-0.5860   
 3rd Qu.:-0.3225    3rd Qu.:-0.5225   3rd Qu.:-0.4385   3rd Qu.:-0.4168   3rd Qu.:-0.2173   
 Max.   : 1.0000    Max.   : 1.0000   Max.   : 1.0000   Max.   : 1.0000   Max.   : 1.0000   
 
 fBodyAccMag-std() fBodyBodyAccJerkMag-mean() fBodyBodyAccJerkMag-std()
 Min.   :-1.0000   Min.   :-1.0000            Min.   :-1.0000          
 1st Qu.:-0.9829   1st Qu.:-0.9898            1st Qu.:-0.9907          
 Median :-0.8547   Median :-0.9290            Median :-0.9255          
 Mean   :-0.6595   Mean   :-0.6208            Mean   :-0.6401          
 3rd Qu.:-0.3823   3rd Qu.:-0.2600            3rd Qu.:-0.3082          
 Max.   : 1.0000   Max.   : 1.0000            Max.   : 1.0000          
 
 fBodyBodyGyroMag-mean() fBodyBodyGyroMag-std() fBodyBodyGyroJerkMag-mean()
 Min.   :-1.0000         Min.   :-1.0000        Min.   :-1.0000            
 1st Qu.:-0.9825         1st Qu.:-0.9781        1st Qu.:-0.9921            
 Median :-0.8756         Median :-0.8275        Median :-0.9453            
 Mean   :-0.6974         Mean   :-0.7000        Mean   :-0.7798            
 3rd Qu.:-0.4514         3rd Qu.:-0.4713        3rd Qu.:-0.6122            
 Max.   : 1.0000         Max.   : 1.0000        Max.   : 1.0000            
 
 fBodyBodyGyroJerkMag-std()
 Min.   :-1.0000           
 1st Qu.:-0.9926           
 Median :-0.9382           
 Mean   :-0.7922           
 3rd Qu.:-0.6437           
 Max.   : 1.0000 


### Appendix B - tidy data set
'data.frame':  10299 obs. of  68 variables:
 $ subject                    : int  1 1 1 1 1 1 1 1 1 1 ...
 $ activity                   : Factor w/ 6 levels "laying","sitting",..: 3 3 3 3 3 ...
 $ tBodyAcc-mean()-X          : num  0.289 0.278 0.28 0.279 0.277 ...
 $ tBodyAcc-mean()-Y          : num  -0.0203 -0.0164 -0.0195 -0.0262 -0.0166 ...
 $ tBodyAcc-mean()-Z          : num  -0.133 -0.124 -0.113 -0.123 -0.115 ...
 $ tBodyAcc-std()-X           : num  -0.995 -0.998 -0.995 -0.996 -0.998 ...
 $ tBodyAcc-std()-Y           : num  -0.983 -0.975 -0.967 -0.983 -0.981 ...
 $ tBodyAcc-std()-Z           : num  -0.914 -0.96 -0.979 -0.991 -0.99 ...
 $ tGravityAcc-mean()-X       : num  0.963 0.967 0.967 0.968 0.968 ...
 $ tGravityAcc-mean()-Y       : num  -0.141 -0.142 -0.142 -0.144 -0.149 ...
 $ tGravityAcc-mean()-Z       : num  0.1154 0.1094 0.1019 0.0999 0.0945 ...
 $ tGravityAcc-std()-X        : num  -0.985 -0.997 -1 -0.997 -0.998 ...
 $ tGravityAcc-std()-Y        : num  -0.982 -0.989 -0.993 -0.981 -0.988 ...
 $ tGravityAcc-std()-Z        : num  -0.878 -0.932 -0.993 -0.978 -0.979 ...
 $ tBodyAccJerk-mean()-X      : num  0.078 0.074 0.0736 0.0773 0.0734 ...
 $ tBodyAccJerk-mean()-Y      : num  0.005 0.00577 0.0031 0.02006 0.01912 ...
 $ tBodyAccJerk-mean()-Z      : num  -0.06783 0.02938 -0.00905 -0.00986 0.01678 ...
 $ tBodyAccJerk-std()-X       : num  -0.994 -0.996 -0.991 -0.993 -0.996 ...
 $ tBodyAccJerk-std()-Y       : num  -0.988 -0.981 -0.981 -0.988 -0.988 ...
 $ tBodyAccJerk-std()-Z       : num  -0.994 -0.992 -0.99 -0.993 -0.992 ...
 $ tBodyGyro-mean()-X         : num  -0.0061 -0.0161 -0.0317 -0.0434 -0.034 ...
 $ tBodyGyro-mean()-Y         : num  -0.0314 -0.0839 -0.1023 -0.0914 -0.0747 ...
 $ tBodyGyro-mean()-Z         : num  0.1077 0.1006 0.0961 0.0855 0.0774 ...
 $ tBodyGyro-std()-X          : num  -0.985 -0.983 -0.976 -0.991 -0.985 ...
 $ tBodyGyro-std()-Y          : num  -0.977 -0.989 -0.994 -0.992 -0.992 ...
 $ tBodyGyro-std()-Z          : num  -0.992 -0.989 -0.986 -0.988 -0.987 ...
 $ tBodyGyroJerk-mean()-X     : num  -0.0992 -0.1105 -0.1085 -0.0912 -0.0908 ...
 $ tBodyGyroJerk-mean()-Y     : num  -0.0555 -0.0448 -0.0424 -0.0363 -0.0376 ...
 $ tBodyGyroJerk-mean()-Z     : num  -0.062 -0.0592 -0.0558 -0.0605 -0.0583 ...
 $ tBodyGyroJerk-std()-X      : num  -0.992 -0.99 -0.988 -0.991 -0.991 ...
 $ tBodyGyroJerk-std()-Y      : num  -0.993 -0.997 -0.996 -0.997 -0.996 ...
 $ tBodyGyroJerk-std()-Z      : num  -0.992 -0.994 -0.992 -0.993 -0.995 ...
 $ tBodyAccMag-mean()         : num  -0.959 -0.979 -0.984 -0.987 -0.993 ...
 $ tBodyAccMag-std()          : num  -0.951 -0.976 -0.988 -0.986 -0.991 ...
 $ tGravityAccMag-mean()      : num  -0.959 -0.979 -0.984 -0.987 -0.993 ...
 $ tGravityAccMag-std()       : num  -0.951 -0.976 -0.988 -0.986 -0.991 ...
 $ tBodyAccJerkMag-mean()     : num  -0.993 -0.991 -0.989 -0.993 -0.993 ...
 $ tBodyAccJerkMag-std()      : num  -0.994 -0.992 -0.99 -0.993 -0.996 ...
 $ tBodyGyroMag-mean()        : num  -0.969 -0.981 -0.976 -0.982 -0.985 ...
 $ tBodyGyroMag-std()         : num  -0.964 -0.984 -0.986 -0.987 -0.989 ...
 $ tBodyGyroJerkMag-mean()    : num  -0.994 -0.995 -0.993 -0.996 -0.996 ...
 $ tBodyGyroJerkMag-std()     : num  -0.991 -0.996 -0.995 -0.995 -0.995 ...
 $ fBodyAcc-mean()-X          : num  -0.995 -0.997 -0.994 -0.995 -0.997 ...
 $ fBodyAcc-mean()-Y          : num  -0.983 -0.977 -0.973 -0.984 -0.982 ...
 $ fBodyAcc-mean()-Z          : num  -0.939 -0.974 -0.983 -0.991 -0.988 ...
 $ fBodyAcc-std()-X           : num  -0.995 -0.999 -0.996 -0.996 -0.999 ...
 $ fBodyAcc-std()-Y           : num  -0.983 -0.975 -0.966 -0.983 -0.98 ...
 $ fBodyAcc-std()-Z           : num  -0.906 -0.955 -0.977 -0.99 -0.992 ...
 $ fBodyAccJerk-mean()-X      : num  -0.992 -0.995 -0.991 -0.994 -0.996 ...
 $ fBodyAccJerk-mean()-Y      : num  -0.987 -0.981 -0.982 -0.989 -0.989 ...
 $ fBodyAccJerk-mean()-Z      : num  -0.99 -0.99 -0.988 -0.991 -0.991 ...
 $ fBodyAccJerk-std()-X       : num  -0.996 -0.997 -0.991 -0.991 -0.997 ...
 $ fBodyAccJerk-std()-Y       : num  -0.991 -0.982 -0.981 -0.987 -0.989 ...
 $ fBodyAccJerk-std()-Z       : num  -0.997 -0.993 -0.99 -0.994 -0.993 ...
 $ fBodyGyro-mean()-X         : num  -0.987 -0.977 -0.975 -0.987 -0.982 ...
 $ fBodyGyro-mean()-Y         : num  -0.982 -0.993 -0.994 -0.994 -0.993 ...
 $ fBodyGyro-mean()-Z         : num  -0.99 -0.99 -0.987 -0.987 -0.989 ...
 $ fBodyGyro-std()-X          : num  -0.985 -0.985 -0.977 -0.993 -0.986 ...
 $ fBodyGyro-std()-Y          : num  -0.974 -0.987 -0.993 -0.992 -0.992 ...
 $ fBodyGyro-std()-Z          : num  -0.994 -0.99 -0.987 -0.989 -0.988 ...
 $ fBodyAccMag-mean()         : num  -0.952 -0.981 -0.988 -0.988 -0.994 ...
 $ fBodyAccMag-std()          : num  -0.956 -0.976 -0.989 -0.987 -0.99 ...
 $ fBodyBodyAccJerkMag-mean() : num  -0.994 -0.99 -0.989 -0.993 -0.996 ...
 $ fBodyBodyAccJerkMag-std()  : num  -0.994 -0.992 -0.991 -0.992 -0.994 ...
 $ fBodyBodyGyroMag-mean()    : num  -0.98 -0.988 -0.989 -0.989 -0.991 ...
 $ fBodyBodyGyroMag-std()     : num  -0.961 -0.983 -0.986 -0.988 -0.989 ...
 $ fBodyBodyGyroJerkMag-mean(): num  -0.992 -0.996 -0.995 -0.995 -0.995 ...
 $ fBodyBodyGyroJerkMag-std() : num  -0.991 -0.996 -0.995 -0.995 -0.995 ...